apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: service-account
    app.kubernetes.io/instance: sco-operator-service-account
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: sco-operator
    app.kubernetes.io/managed-by: kustomize
  name: sco-operator-service-account
  namespace: sco-system
